const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.gamepad,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{direcao: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{Protagonista: 0},
	{Sólido: 0},
	{Mosaico: 0},
	{Mira: 0},
	{Mouse: 0},
	{Gamepad: 0},
	{Casa1: 0},
	{Casa2: 0},
	{Mosaico2: 0},
	{Mosaico3: 0},
	{Mosaico4: 0},
	{Teleporte: 0},
	{Teleporte2: 0},
	{NPC: 0},
	{Sprite: 0},
	{Mosaico5: 0},
	{Mosaico6: 0},
	{Teleporte3: 0},
	{Sprite3: 0},
	{Inicio: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Texto: 0},
	{Sprite6: 0},
	{SAIR: 0},
	{Navegador: 0},
	{Texto2: 0},
	{Texto3: 0},
	{primeiro: 0},
	{fim: 0},
	{emy: 0},
	{Sprite2: 0},
	{Áudio: 0},
	{fala: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	Protagonista: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Mira: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Casa1: class extends self.ISpriteInstance {},
	Casa2: class extends self.ISpriteInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Mosaico3: class extends self.ITilemapInstance {},
	Mosaico4: class extends self.ITilemapInstance {},
	Teleporte: class extends self.ISpriteInstance {},
	Teleporte2: class extends self.ISpriteInstance {},
	NPC: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mosaico5: class extends self.ITilemapInstance {},
	Mosaico6: class extends self.ITilemapInstance {},
	Teleporte3: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Inicio: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	SAIR: class extends self.ITextInstance {},
	Navegador: class extends self.IInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	primeiro: class extends self.ISpriteInstance {},
	fim: class extends self.ISpriteInstance {},
	emy: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	fala: class extends self.ITextInstance {}
}