const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.gamepad,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Browser.Acts.Reload,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{direcao: 0},
	{"8Direções": 0},
	{Protagonista: 0},
	{Sólido: 0},
	{Mosaico: 0},
	{CentrarEm: 0},
	{Mira: 0},
	{Mouse: 0},
	{Atrelar: 0},
	{Camera: 0},
	{Gamepad: 0},
	{Casa1: 0},
	{Casa2: 0},
	{Mosaico2: 0},
	{Mosaico3: 0},
	{Mosaico4: 0},
	{Teleporte: 0},
	{Teleporte2: 0},
	{NPCGlenda: 0},
	{Sprite: 0},
	{Mosaico5: 0},
	{Mosaico6: 0},
	{Sprite2: 0},
	{Teleporte3: 0},
	{Sprite3: 0},
	{Inicio: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Texto: 0},
	{Sprite6: 0},
	{SAIR: 0},
	{Navegador: 0},
	{Sprite7: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite8: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Sprite11: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	Protagonista: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Mira: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Camera: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	Casa1: class extends self.ISpriteInstance {},
	Casa2: class extends self.ISpriteInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Mosaico3: class extends self.ITilemapInstance {},
	Mosaico4: class extends self.ITilemapInstance {},
	Teleporte: class extends self.ISpriteInstance {},
	Teleporte2: class extends self.ISpriteInstance {},
	NPCGlenda: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mosaico5: class extends self.ITilemapInstance {},
	Mosaico6: class extends self.ITilemapInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Teleporte3: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Inicio: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	SAIR: class extends self.ITextInstance {},
	Navegador: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {}
}